### PR TITLE
fix conditions for feeds in multi fetchers

### PR DESCRIPTION
**Pull request by DZariusz**
previous conditions might be wrong or not deterministics. Now we will be using strict fetchers name

### CODE REVIEW

**Review by gagiuntoli — APPROVED** [review]
It looks good to me.

I just think that the "filter" way of doing it could be slightly improved if we can group the inputs before passing it to the fetchers. This operation seems to anyway not consume too much but there are operations inside this multiprocessors, like the input separation, that could be delegated to another service (the one that calls this multiprocessors). In this way this for loops are not repeated everywhere and there is no need to select the right fetcher name.

**Comment by DZariusz** [comment]
> I just think that the "filter" way of doing it...

you talking about the code I added, this `if`s or about this weird `order` method?

**Comment by gagiuntoli** [comment]
> > I just think that the "filter" way of doing it...
> 
> you talking about the code I added, this `if`s or about this weird `order` method?

About this for example:

```typescript
    feedInputs.forEach((fetcher) => {
      if (!fetcher.name.includes(FetcherName.UNISWAP_V3)) return;

      const {fromChain, base, quote, amountInDecimals} = fetcher.params as UniswapV3MultiFetcherParams;
      params.push({fromChain, base, quote, amountInDecimals});
    });
```

This seems to be done on every multiprocessor every time they call `apply`.

**Comment by DZariusz** [comment]
> This seems to be done on every multiprocessor every time they call `apply`.

but there are different params, so code is not the same and I see no way of creating general method for it (unless we use `ief-else-if...` sequence - but this does not looks like good idea.

As I mentioned before, I would change return value to `key-value` and then we will work only with feeds that belong to each fetcher, without this arrays. but this would be separate PR.

**Comment by gagiuntoli** [comment]
> > This seems to be done on every multiprocessor every time they call `apply`.
> 
> but there are different params, so code is not the same and I see no way of creating general method for it (unless we use `if-else-if...` sequence - but this does not looks like good idea.
> 
> As I mentioned before, I would change return value to `key-value` and then we will work only with feeds that belong to each fetcher, without this arrays. but this would be separate PR.

Yes, that is what I mean and prefer. Seems like much cleaner to do that (also more efficient).

**Pull request merged**
